version: '3'

# 系统配置
app:
  env: debug  # 合法选项 "" (默认为空 = debug ) "debug" "release" "test"
  host: 0.0.0.0
  port: 8088
  public_path:
  doamin: localhost # 设置 set-cookie httpOnly=true 使用，能有效防止 csrf 攻击

# 数据库配置
mysql:
  host: 127.0.0.1
  port: 3306
  user: root
  pwd: root123123
  db: go_web_demo
  prefix:
  max_idle: 10
  max_active: 10

# 日志配置
log:
  path:
  level: info # 合法选项 "panic" "fatal" "error" "warn" "warning" "info" "debug" "trace"
  max_age: 72 #设置文件清理前的最长保存时间(小时)
  rorate_time: 1 #设置日志分割的时间，隔多久分割一次（小时）

# rbac 权限配置
casbin:
  path:

# 验证码配置
captcha:
  length: 4
  width: 150
  height: 50
#  str: 234567890abcdefghjkmnpqrstuvwxyz
  str: 1234567890
  font:
    - wqy-microhei.ttc
  noise: 100
  line: 3

# json web token 配置
jwt:
  key: qazwsxedc!@#$%
  exp_time: 100 #小时